apiVersion: apps/v1
kind: Deployment
metadata:
  name: desci-server-dev
  labels:
    App: DesciServerDev
spec:
  replicas: 6
  revisionHistoryLimit: 8
  selector:
    matchLabels:
      App: DesciServerDev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: app-vault-reader
        vault.hashicorp.com/agent-inject-secret-config: secrets/desci-server/dev/db
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secrets/desci-server/dev/db" -}}
          export PG_HOST={{ .Data.host }}
          export PG_PORT={{ .Data.port }}
          export POSTGRES_USER={{ .Data.user }}
          export POSTGRES_PASSWORD={{ .Data.password }}
          export POSTGRES_DB={{ .Data.db }}
          export DATABASE_URL={{ .Data.url }}
          export IPFS_NODE_URL="http://ipfs-gateway-staging-internal.default.svc.cluster.local:5001"
          export NODE_ENV=production
          echo "dbset"; 
          {{- end -}}
          {{- with secret "secrets/desci-server/dev/app" -}}
          echo "appstart"; 
          export PINO_LOG_LEVEL={{ .Data.PINO_LOG_LEVEL }}
          export JWT_SECRET={{ .Data.JWT_SECRET }}
          export JWT_EXPIRATION=15m
          export SESSION_KEY={{ .Data.SESSION_KEY }}
          export COOKIE_DOMAIN={{ .Data.COOKIE_DOMAIN }}
          export OLD_COOKIE_DOMAINS={{ .Data.OLD_COOKIE_DOMAINS }}
          export ORCID_API_DOMAIN={{ .Data.ORCID_API_DOMAIN }}
          export DPID_URL_OVERRIDE={{ .Data.DPID_URL_OVERRIDE }}
          export ORCID_CLIENT_ID={{ .Data.ORCID_CLIENT_ID }}
          export ORCID_CLIENT_SECRET={{ .Data.ORCID_CLIENT_SECRET }}
          export ARWEAVE_ENABLED=0
          export ARWEAVE_HOST=
          export ARWEAVE_PORT=1984
          export ARWEAVE_PROTOCOL=http
          export ARWEAVE_PUBKEY=
          export ARWAVE_SECRET_PRIVATE_KEY_SECRET=
          export REDIS_HOST={{ .Data.REDIS_HOST }}
          export REDIS_PORT={{ .Data.REDIS_PORT }}
          export REDIS_URL={{ .Data.REDIS_URL }}
          export SERVER_URL={{ .Data.SERVER_URL }}
          export DAPP_URL={{ .Data.DAPP_URL }}
          export SENDGRID_API_KEY={{ .Data.SENDGRID_API_KEY }}
          export SENDGRID_TEMPLATE_ID_MAP={{ .Data.SENDGRID_TEMPLATE_ID_MAP }}
          export SHOULD_SEND_EMAIL=true
          export AWS_ACCESS_KEY_ID={{ .Data.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY={{ .Data.AWS_SECRET_ACCESS_KEY }}
          export AWS_S3_BUCKET_NAME={{ .Data.AWS_S3_BUCKET_NAME }}
          export AWS_S3_BUCKET_REGION={{ .Data.AWS_S3_BUCKET_REGION }}
          export THEGRAPH_API_URL={{ .Data.THEGRAPH_API_URL }}
          export HOT_WALLET_KEY={{ .Data.HOT_WALLET_KEY }}
          export REGISTRY_OWNER_PKEY={{ .Data.REGISTRY_OWNER_PKEY }}
          export CSO_CLASSIFIER_API={{ .Data.CSO_CLASSIFIER_API }}
          export VSCODE_ACCESS_TOKEN={{ .Data.VSCODE_ACCESS_TOKEN }}
          export NODES_MEDIA_SERVER_URL={{ .Data.NODES_MEDIA_SERVER_URL }}
          export OTEL_SERVICE_NAME={{ .Data.OTEL_SERVICE_NAME }}
          export HONEYCOMB_API_KEY={{ .Data.HONEYCOMB_API_KEY }}
          export DISCORD_NOTIFICATIONS_WEBHOOK_URL={{ .Data.DISCORD_NOTIFICATIONS_WEBHOOK_URL }}
          export DISCORD_NOTIFICATIONS_DOI_WEBHOOK_URL={{ .Data.DISCORD_NOTIFICATIONS_DOI_WEBHOOK_URL }}
          export PUBLIC_IPFS_RESOLVER={{ .Data.PUBLIC_IPFS_RESOLVER }}
          export MEDIA_SECRET_KEY={{ .Data.MEDIA_SECRET_KEY }}
          export ESTUARY_API_KEY={{ .Data.ESTUARY_API_KEY }}
          export ESTUARY_API_URL={{ .Data.ESTUARY_API_URL }}
          export REPO_SERVER_URL={{ .Data.REPO_SERVER_URL }}
          export REPO_SERVICE_SECRET_KEY={{ .Data.REPO_SERVICE_SECRET_KEY }}
          export ISOLATED_MEDIA_SERVER_URL={{ .Data.ISOLATED_MEDIA_SERVER_URL }}
          export IPFS_READ_ONLY_GATEWAY_SERVER_URL={{ .Data.IPFS_READ_ONLY_GATEWAY_SERVER_URL }}
          export ETHEREUM_RPC_URL={{ .Data.ETHEREUM_RPC_URL }}
          export GOOGLE_CLIENT_ID={{ .Data.GOOGLE_CLIENT_ID }}
          export DOI_PREFIX={{ .Data.DOI_PREFIX }}
          export CROSSREF_EMAIL={{ .Data.CROSSREF_EMAIL }}
          export CROSSREF_DOI_URL={{ .Data.CROSSREF_DOI_URL }}
          export CROSSREF_LOGIN={{ .Data.CROSSREF_LOGIN }}
          export CROSSREF_PASSWORD={{ .Data.CROSSREF_PASSWORD }}
          export CROSSREF_METADATA_API={{ .Data.CROSSREF_METADATA_API }}
          export CROSSREF_ADMIN_API={{ .Data.CROSSREF_ADMIN_API }}
          export CROSSREF_NOTIFY_ENDPOINT={{ .Data.CROSSREF_NOTIFY_ENDPOINT }}
          export AUTOMATED_METADATA_API="{{ .Data.AUTOMATED_METADATA_API }}"
          export AUTOMATED_METADATA_API_KEY="{{ .Data.AUTOMATED_METADATA_API_KEY }}"
          export ELASTIC_SEARCH_NODE_URL="{{ .Data.ELASTIC_SEARCH_NODE_URL }}"
          export ELASTIC_SEARCH_USER="{{ .Data.ELASTIC_SEARCH_USER }}"
          export ELASTIC_SEARCH_PW="{{ .Data.ELASTIC_SEARCH_PW }}"
          export ELASTIC_SEARCH_WRITE_API_KEY="{{ .Data.ELASTIC_SEARCH_WRITE_API_KEY }}"
          export OPEN_ALEX_DATABASE_URL="{{ .Data.OPEN_ALEX_DATABASE_URL }}"
          export SCORE_GEN_SERVER="{{ .Data.SCORE_GEN_SERVER }}"
          export SCORE_RESULT_API="{{ .Data.SCORE_RESULT_API }}"
          export AI_CID_SEND_SERVER="{{ .Data.AI_CID_SEND_SERVER }}"
          export CLOUDFLARE_WORKER_API=https://nodes-dev-sync.desci.com
          export CLOUDFLARE_WORKER_API_SECRET="{{ .Data.CLOUDFLARE_WORKER_API_SECRET }}"
          export ENABLE_WORKERS_API=true
          export LOG_ENCRYPTION_KEY="{{ .Data.LOG_ENCRYPTION_KEY }}"
          export ORCID_PUBLIC_API="{{ .Data.ORCID_PUBLIC_API }}"
          export GUEST_IPFS_NODE_URL="{{ .Data.GUEST_IPFS_NODE_URL }}"
          export AWS_SQS_ACCESS_KEY_ID="{{ .Data.AWS_SQS_ACCESS_KEY_ID }}"
          export AWS_SQS_SECRET_ACCESS_KEY="{{ .Data.AWS_SQS_SECRET_ACCESS_KEY }}"
          export AWS_SQS_REGION="{{ .Data.AWS_SQS_REGION }}"
          export AWS_SQS_DATA_MIGRATION_QUEUE_URL="{{ .Data.AWS_SQS_DATA_MIGRATION_QUEUE_URL }}"
          export AWS_SQS_ML_TOOL_QUEUE_URL="{{ .Data.AWS_SQS_ML_TOOL_QUEUE_URL }}"
          export ML_REFEREE_GET_PRESIGNED_URL="{{ .Data.ML_REFEREE_GET_PRESIGNED_URL }}"
          export ML_REFEREE_TRIGGER_CID="{{ .Data.ML_REFEREE_TRIGGER_CID }}"
          export ML_REFEREE_FINDER_RESULT="{{ .Data.ML_REFEREE_FINDER_RESULT }}"
          export ENABLE_GUEST_MODE="{{ .Data.ENABLE_GUEST_MODE }}"
          export MIXPANEL_TOKEN="{{ .Data.MIXPANEL_TOKEN }}"
          export SCIWEAVE_GOOGLE_CLIENT_ID="{{ .Data.SCIWEAVE_GOOGLE_CLIENT_ID }}"
          export STRIPE_WEBHOOK_SECRET="{{ .Data.STRIPE_WEBHOOK_SECRET }}"
          export STRIPE_SECRET_KEY="{{ .Data.STRIPE_SECRET_KEY }}"
          export INTERNAL_SERVICE_SECRET="{{ .Data.INTERNAL_SERVICE_SECRET }}"
          export STRIPE_OMNI_CHATS_MONTHLY_PRICE_ID="{{ .Data.STRIPE_OMNI_CHATS_MONTHLY_PRICE_ID }}"
          export STRIPE_OMNI_CHATS_ANNUAL_PRICE_ID="{{ .Data.STRIPE_OMNI_CHATS_ANNUAL_PRICE_ID }}"
          export SCIWEAVE_FREE_LIMIT="{{ .Data.SCIWEAVE_FREE_LIMIT }}"
          export SCIWEAVE_SENDGRID_TEMPLATE_ID_MAP={{ .Data.SCIWEAVE_SENDGRID_TEMPLATE_ID_MAP }}
          export DEBUG_TEST=0;
          echo "appfinish";
          {{- end -}}
      labels:
        App: DesciServerDev
    spec:
      containers:
        - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/desci-server-dev:latest
          name: desci-server-dev
          command: ['/bin/bash', '-c']
          args:
            - echo "SOURCING ENV"; source /vault/secrets/config; NODE_PATH=./dist node ./dist/index.js;
          ports:
            - containerPort: 5420
              name: server-api
            - containerPort: 5445
              name: ws-api
          resources:
            limits:
              cpu: '0.7'
              memory: 5Gi
            requests:
              cpu: '0.6'
              memory: 5Gi
          # restart pod after failureThreshold*periodSeconds total seconds
          livenessProbe:
            httpGet:
              path: /readyz
              port: server-api
            failureThreshold: 80
            periodSeconds: 3
          # temporarily stop sending traffic to pod after failureThreshold*periodSeconds total seconds
          readinessProbe:
            httpGet:
              path: /readyz
              port: server-api
            failureThreshold: 3
            periodSeconds: 1
          # wait for pod to start for failureThreshold*periodSeconds total seconds
          startupProbe:
            httpGet:
              path: /readyz
              port: server-api
            failureThreshold: 200
            periodSeconds: 1

      serviceAccountName: 'vault-auth'
---
apiVersion: v1
kind: Service
metadata:
  name: desci-server-dev-service
  labels:
    App: DesciServerDev
spec:
  type: LoadBalancer
  selector:
    App: DesciServerDev
  ports:
    - protocol: TCP
      name: api
      port: 80
      targetPort: 5420
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: desci-server-dev-ingress-new
  annotations:
    kubernetes.io/ingress.class: 'alb'
    alb.ingress.kubernetes.io/scheme: 'internet-facing'
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:523044037273:certificate/b6ddf370-5957-4996-bc09-4f48894c0c1f
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: 'nodes-api-dev.desci.com'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: desci-server-dev-service
                port:
                  number: 80
