apiVersion: batch/v1
kind: Job
metadata:
  name: desci-server-migration
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: app-vault-reader
        vault.hashicorp.com/agent-inject-secret-config: secrets/desci-server/staging/db
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secrets/desci-server/staging/db" -}}
          export PG_HOST={{ .Data.host }}
          export PG_PORT={{ .Data.port }}
          export POSTGRES_USER={{ .Data.user }}
          export POSTGRES_PASSWORD={{ .Data.password }}
          export POSTGRES_DB={{ .Data.db }}
          export DATABASE_URL={{ .Data.url }}
          export IPFS_NODE_URL="http://ipfs-gateway-staging-internal.default.svc.cluster.local:5001"
          export NODE_ENV=production
          echo "dbset"; 
          {{- end -}}
          {{- with secret "secrets/desci-server/staging/app" -}}
          echo "appstart"; 
          export JWT_SECRET={{ .Data.JWT_SECRET }}
          export JWT_EXPIRATION=15m
          export SESSION_KEY={{ .Data.SESSION_KEY }}
          export ORCID_CLIENT_ID={{ .Data.ORCID_CLIENT_ID }}
          export ORCID_CLIENT_SECRET={{ .Data.ORCID_CLIENT_SECRET }}
          export ARWEAVE_ENABLED=0
          export ARWEAVE_HOST=
          export ARWEAVE_PORT=1984
          export ARWEAVE_PROTOCOL=http
          export ARWEAVE_PUBKEY=
          export ARWAVE_SECRET_PRIVATE_KEY_SECRET=
          export SERVER_URL={{ .Data.SERVER_URL }}
          export DAPP_URL={{ .Data.DAPP_URL }}
          {{- end -}}
    spec:
      containers:
        - name: desci-server
          image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/desci-server:latest
          command: ['/bin/bash', '-c']
          args:
            - echo "SOURCING ENV"; source /vault/secrets/config; npx prisma migrate deploy
      restartPolicy: Never
  backoffLimit: 4
