services:
  postgres:
    container_name: 'openalex_db'
    image: 'ankane/pgvector'
    restart: on-failure
    healthcheck:
      test: 'pg_isready -U postgres -d postgres'
      interval: 5s
      timeout: 15s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: '3'
    ports:
      - '5438:5432'
    volumes:
      - ./postgres/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./postgres/sql/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  openalex-importer:
    container_name: 'openalex-importer'
    restart: on-failure
    build: .
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
