name: test
services:
  nodes_test_db:
    container_name: "nodes_test_db"
    image: "postgres:12.6-alpine"
    restart: on-failure
    healthcheck:
      test: "pg_isready -U walter -d postgres"
      interval: 5s
      timeout: 15s
      retries: 5
    env_file:
      - .env.test
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "5434:5432"
    # volumes:
    #   - ./database/test:/var/lib/postgresql/data/

  nodes_backend_test:
    container_name: "nodes_backend_test"
    build: .
    entrypoint: /bin/sh './desci-server/scripts/be-node-test.sh'
    env_file:
      - .env.test
    environment:
      - RUN_DEV=${RUN_DEV:-0}
    ports:
      - "5421:5420"
      - "9227:9227"
      - "5557:5555"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      nodes_test_sync_service:
        condition: service_healthy
      nodes_test_db:
        condition: service_healthy
      nodes_test_ipfs:
        condition: service_healthy
    volumes:
      - .:/app/
    healthcheck:
      test: curl -f http://localhost:5421/readyz || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    #   - /app/node_modules
    # volumes:
    #   - ./tmp/nebulus:/tmp/nebulus

  nodes_test_ipfs:
    image: ipfs/kubo:v0.26.0
    environment:
      IPFS_SWARM_KEY: "/key/swarm/psk/1.0.0/\n/base16/\n9d002c50635a479d29dcc0ccb49d862952a0dcc52baddd253167adcd496c8d04"
    ports:
      - "5003:5001"
      - "8091:8080"
    command:
      # These are defaults from the go-ipfs dockerfile CMD
      - "daemon"
      - "--migrate=true"
      - "--agent-version-suffix=docker"
      # This is necessary before ceramic ships Recon, the new tip gossip protocol
      - "--enable-pubsub-experiment"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./local-data/test/ipfs:/data/ipfs
    healthcheck:
      test: ipfs ls QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn || exit 1
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 2s

  nodes_test_sync_service:
    container_name: nodes_sync_test_worker
    build:
      context: ./sync-server
      dockerfile: Dockerfile
    image: worker_test
    ports:
      - "5446:5445"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./sync-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      nodes_test_db:
        condition: service_healthy
    env_file:
      - ./sync-server/.env.test
    healthcheck:
      test: curl -f http://localhost:5445/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s

  ceramic-one-test:
    container_name: ceramic_one_test
    image: public.ecr.aws/r5b3e0r5/3box/ceramic-one:0.56.0
    restart: on-failure
    ports:
      - 5101:5101 # RPC
      - 5102:5102 # flight SQL (> v0.53.0)
    environment:
      CERAMIC_ONE_STORE_DIR: "/data/ceramic-one"
      CERAMIC_ONE_P2P_KEY_DIR: "/data/ceramic-one"
      CERAMIC_ONE_BIND_ADDRESS: "0.0.0.0:5101"
      CERAMIC_ONE_SWARM_ADDRESSES: "/ip4/0.0.0.0/tcp/4101,/ip4/0.0.0.0/udp/4102/quic-v1"
      CERAMIC_ONE_METRICS_BIND_ADDRESS: "0.0.0.0:9465"
      CERAMIC_ONE_FLIGHT_SQL_BIND_ADDRESS: "0.0.0.0:5102"
      CERAMIC_ONE_NETWORK: "inmemory"
      RUST_LOG: "warn"
      CERAMIC_ONE_LOG_FORMAT: "multi-line"
    volumes:
      - ../local-data/test/ceramic-one:/data/ceramic-one
    healthcheck:
      test:
        [
          "CMD",
          "ceramic-one",
          "query",
          "statement-query",
          "select null from event_states limit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

