name: test
services:
  nodes_test_db:
    container_name: "nodes_test_db"
    image: "postgres:12.6-alpine"
    restart: on-failure
    healthcheck:
      test: "pg_isready -U walter -d postgres"
      interval: 5s
      timeout: 15s
      retries: 5
    env_file:
      - .env.test
    ports:
      - "5434:5432"
    # volumes:
    #   - ./database/test:/var/lib/postgresql/data/

  nodes_backend_test:
    build: .
    entrypoint: /bin/sh './desci-server/scripts/be-node-test.sh'
    env_file:
      - .env.test
    ports:
      - "5421:5420"
      - "9227:9227"
      - "5557:5555"
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      nodes_test_sync_service:
        condition: service_started
      nodes_test_db:
        condition: service_healthy
      nodes_test_ipfs:
        condition: service_started
      nodes_test_repo_service:
        condition: service_healthy
    links:
      - nodes_test_db
    container_name: "nodes_backend_test"
    volumes:
      - .:/app/
    #   - /app/node_modules
    # volumes:
    #   - ./tmp/nebulus:/tmp/nebulus

  nodes_test_ipfs:
    image: ipfs/go-ipfs:v0.13.0
    environment:
      IPFS_SWARM_KEY: "/key/swarm/psk/1.0.0/\n/base16/\n9d002c50635a479d29dcc0ccb49d862952a0dcc52baddd253167adcd496c8d04"
    ports:
      - "5003:5001"
      - "8091:8080"
    volumes:
      - ./local-data/test/ipfs:/data/ipfs

  nodes_test_repo_service:
    container_name: "nodes_test_repo_service"
    entrypoint: /bin/sh './desci-repo/scripts/be-node-test.sh'
    build: ./desci-repo
    env_file:
      - ./desci-repo/.env.test
    ports:
      - "5485:5484"
      # - "5446:5445"
    extra_hosts:
      - host.docker.internal:host-gateway
    healthcheck:
      test: curl -f http://localhost:5484/readyz || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - nodes_test_db
    links:
      - nodes_test_db
    volumes:
      - .:/app/
      - ./local-data/yarn_cache:/root/.yarn

  nodes_test_sync_service:
    build:
      context: ./sync-server
      dockerfile: Dockerfile
    container_name: nodes_sync_test_worker
    image: worker_test
    ports:
      - "5446:5445"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./sync-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - nodes_test_db
    env_file:
      - ./sync-server/.env.test
