version: '3'

services:
  desci_nodes_backend:
    command: /bin/sh -c "echo 'Running API on production!' && npm run build && npm start"
    ports:
      - '5420:5420'
    env_file:
      - ./config/stage.env
