version: "3"

services:
  desci_nodes_backend:
    container_name: "desci_nodes_backend"
    build: .
    restart: always
    volumes:
      - .:/app/
      - /app/node_modules
# UNCOMMENT FOR LOCAL DEV OF NODES_MEDIA
# nodes_media:
#   container_name: 'nodes_media'
#   build: ./nodes-media
#   restart: always
#   volumes:
#     - ./nodes-media:/app/
#     - /app/node_modules
