services:
  desci_nodes_backend:
    container_name: "desci_nodes_backend"
    build:
      context: desci-server
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/app/
      - /app/node_modules
