services:
  desci_sync:
    build: ./sync-server
    container_name: desci_sync
    image: worker
    env_file:
      - ./sync-server/.env
    ports:
      - "5445:8080"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./local-data/.storage/cache:/worker/cache
      - ./sync-server/worker.capnp:/worker/worker.capnp
    depends_on:
      db_postgres:
        condition: service_healthy
