/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IDpidRegistryInterface extends utils.Interface {
  contractName: "IDpidRegistry";
  functions: {
    "get(bytes32,uint256)": FunctionFragment;
    "getOrganization(bytes32)": FunctionFragment;
    "put(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "get",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganization",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "put",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "get", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "put", data: BytesLike): Result;

  events: {};
}

export interface IDpidRegistry extends BaseContract {
  contractName: "IDpidRegistry";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDpidRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    get(
      prefix: BytesLike,
      entryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getOrganization(
      prefix: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;

    put(
      prefix: BytesLike,
      entry: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  get(
    prefix: BytesLike,
    entryId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getOrganization(
    prefix: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string]>;

  put(
    prefix: BytesLike,
    entry: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    get(
      prefix: BytesLike,
      entryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrganization(
      prefix: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;

    put(
      prefix: BytesLike,
      entry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    get(
      prefix: BytesLike,
      entryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrganization(
      prefix: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    put(
      prefix: BytesLike,
      entry: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    get(
      prefix: BytesLike,
      entryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrganization(
      prefix: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    put(
      prefix: BytesLike,
      entry: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
