"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.VersionedERC721V2__factory = exports.VersionedERC721__factory = exports.TestERC721__factory = exports.ResearchObjectV2__factory = exports.ResearchObject__factory = exports.ResearchObjectMigrated__factory = exports.IDpidRegistry__factory = exports.DpidRegistry__factory = exports.IERC165__factory = exports.ERC165__factory = exports.IERC721Receiver__factory = exports.IERC721__factory = exports.IERC721Metadata__factory = exports.ERC721__factory = exports.IERC165Upgradeable__factory = exports.ERC165Upgradeable__factory = exports.ContextUpgradeable__factory = exports.IERC721Upgradeable__factory = exports.IERC721ReceiverUpgradeable__factory = exports.IERC721MetadataUpgradeable__factory = exports.ERC721Upgradeable__factory = exports.Initializable__factory = exports.OwnableUpgradeable__factory = void 0;
var OwnableUpgradeable__factory_1 = require("./factories/OwnableUpgradeable__factory");
__createBinding(exports, OwnableUpgradeable__factory_1, "OwnableUpgradeable__factory");
var Initializable__factory_1 = require("./factories/Initializable__factory");
__createBinding(exports, Initializable__factory_1, "Initializable__factory");
var ERC721Upgradeable__factory_1 = require("./factories/ERC721Upgradeable__factory");
__createBinding(exports, ERC721Upgradeable__factory_1, "ERC721Upgradeable__factory");
var IERC721MetadataUpgradeable__factory_1 = require("./factories/IERC721MetadataUpgradeable__factory");
__createBinding(exports, IERC721MetadataUpgradeable__factory_1, "IERC721MetadataUpgradeable__factory");
var IERC721ReceiverUpgradeable__factory_1 = require("./factories/IERC721ReceiverUpgradeable__factory");
__createBinding(exports, IERC721ReceiverUpgradeable__factory_1, "IERC721ReceiverUpgradeable__factory");
var IERC721Upgradeable__factory_1 = require("./factories/IERC721Upgradeable__factory");
__createBinding(exports, IERC721Upgradeable__factory_1, "IERC721Upgradeable__factory");
var ContextUpgradeable__factory_1 = require("./factories/ContextUpgradeable__factory");
__createBinding(exports, ContextUpgradeable__factory_1, "ContextUpgradeable__factory");
var ERC165Upgradeable__factory_1 = require("./factories/ERC165Upgradeable__factory");
__createBinding(exports, ERC165Upgradeable__factory_1, "ERC165Upgradeable__factory");
var IERC165Upgradeable__factory_1 = require("./factories/IERC165Upgradeable__factory");
__createBinding(exports, IERC165Upgradeable__factory_1, "IERC165Upgradeable__factory");
var ERC721__factory_1 = require("./factories/ERC721__factory");
__createBinding(exports, ERC721__factory_1, "ERC721__factory");
var IERC721Metadata__factory_1 = require("./factories/IERC721Metadata__factory");
__createBinding(exports, IERC721Metadata__factory_1, "IERC721Metadata__factory");
var IERC721__factory_1 = require("./factories/IERC721__factory");
__createBinding(exports, IERC721__factory_1, "IERC721__factory");
var IERC721Receiver__factory_1 = require("./factories/IERC721Receiver__factory");
__createBinding(exports, IERC721Receiver__factory_1, "IERC721Receiver__factory");
var ERC165__factory_1 = require("./factories/ERC165__factory");
__createBinding(exports, ERC165__factory_1, "ERC165__factory");
var IERC165__factory_1 = require("./factories/IERC165__factory");
__createBinding(exports, IERC165__factory_1, "IERC165__factory");
var DpidRegistry__factory_1 = require("./factories/DpidRegistry__factory");
__createBinding(exports, DpidRegistry__factory_1, "DpidRegistry__factory");
var IDpidRegistry__factory_1 = require("./factories/IDpidRegistry__factory");
__createBinding(exports, IDpidRegistry__factory_1, "IDpidRegistry__factory");
var ResearchObjectMigrated__factory_1 = require("./factories/ResearchObjectMigrated__factory");
__createBinding(exports, ResearchObjectMigrated__factory_1, "ResearchObjectMigrated__factory");
var ResearchObject__factory_1 = require("./factories/ResearchObject__factory");
__createBinding(exports, ResearchObject__factory_1, "ResearchObject__factory");
var ResearchObjectV2__factory_1 = require("./factories/ResearchObjectV2__factory");
__createBinding(exports, ResearchObjectV2__factory_1, "ResearchObjectV2__factory");
var TestERC721__factory_1 = require("./factories/TestERC721__factory");
__createBinding(exports, TestERC721__factory_1, "TestERC721__factory");
var VersionedERC721__factory_1 = require("./factories/VersionedERC721__factory");
__createBinding(exports, VersionedERC721__factory_1, "VersionedERC721__factory");
var VersionedERC721V2__factory_1 = require("./factories/VersionedERC721V2__factory");
__createBinding(exports, VersionedERC721V2__factory_1, "VersionedERC721V2__factory");
