/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IRelayHub {
  export type RelayHubConfigStruct = {
    maxWorkerCount: BigNumberish;
    gasReserve: BigNumberish;
    postOverhead: BigNumberish;
    gasOverhead: BigNumberish;
    minimumUnstakeDelay: BigNumberish;
    devAddress: string;
    devFee: BigNumberish;
    baseRelayFee: BigNumberish;
    pctRelayFee: BigNumberish;
  };

  export type RelayHubConfigStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    number,
    BigNumber,
    number
  ] & {
    maxWorkerCount: BigNumber;
    gasReserve: BigNumber;
    postOverhead: BigNumber;
    gasOverhead: BigNumber;
    minimumUnstakeDelay: BigNumber;
    devAddress: string;
    devFee: number;
    baseRelayFee: BigNumber;
    pctRelayFee: number;
  };
}

export declare namespace GsnTypes {
  export type RelayDataStruct = {
    maxFeePerGas: BigNumberish;
    maxPriorityFeePerGas: BigNumberish;
    transactionCalldataGasUsed: BigNumberish;
    relayWorker: string;
    paymaster: string;
    forwarder: string;
    paymasterData: BytesLike;
    clientId: BigNumberish;
  };

  export type RelayDataStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    string,
    BigNumber
  ] & {
    maxFeePerGas: BigNumber;
    maxPriorityFeePerGas: BigNumber;
    transactionCalldataGasUsed: BigNumber;
    relayWorker: string;
    paymaster: string;
    forwarder: string;
    paymasterData: string;
    clientId: BigNumber;
  };

  export type RelayRequestStruct = {
    request: IForwarder.ForwardRequestStruct;
    relayData: GsnTypes.RelayDataStruct;
  };

  export type RelayRequestStructOutput = [
    IForwarder.ForwardRequestStructOutput,
    GsnTypes.RelayDataStructOutput
  ] & {
    request: IForwarder.ForwardRequestStructOutput;
    relayData: GsnTypes.RelayDataStructOutput;
  };
}

export declare namespace IForwarder {
  export type ForwardRequestStruct = {
    from: string;
    to: string;
    value: BigNumberish;
    gas: BigNumberish;
    nonce: BigNumberish;
    data: BytesLike;
    validUntilTime: BigNumberish;
  };

  export type ForwardRequestStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    from: string;
    to: string;
    value: BigNumber;
    gas: BigNumber;
    nonce: BigNumber;
    data: string;
    validUntilTime: BigNumber;
  };
}

export interface IRelayHubInterface extends utils.Interface {
  contractName: "IRelayHub";
  functions: {
    "addRelayWorkers(address[])": FunctionFragment;
    "aggregateGasleft()": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "calculateCharge(uint256,(uint256,uint256,uint256,address,address,address,bytes,uint256))": FunctionFragment;
    "calculateDevCharge(uint256)": FunctionFragment;
    "depositFor(address)": FunctionFragment;
    "deprecateHub(uint256)": FunctionFragment;
    "escheatAbandonedRelayBalance(address)": FunctionFragment;
    "getBatchGateway()": FunctionFragment;
    "getConfiguration()": FunctionFragment;
    "getCreationBlock()": FunctionFragment;
    "getDeprecationTime()": FunctionFragment;
    "getMinimumStakePerToken(address)": FunctionFragment;
    "getPenalizer()": FunctionFragment;
    "getRelayRegistrar()": FunctionFragment;
    "getStakeManager()": FunctionFragment;
    "getWorkerCount(address)": FunctionFragment;
    "getWorkerManager(address)": FunctionFragment;
    "isDeprecated()": FunctionFragment;
    "isRelayEscheatable(address)": FunctionFragment;
    "onRelayServerRegistered(address)": FunctionFragment;
    "penalize(address,address)": FunctionFragment;
    "relayCall(string,uint256,((address,address,uint256,uint256,uint256,bytes,uint256),(uint256,uint256,uint256,address,address,address,bytes,uint256)),bytes,bytes)": FunctionFragment;
    "setConfiguration((uint256,uint256,uint256,uint256,uint256,address,uint8,uint80,uint16))": FunctionFragment;
    "setMinimumStakes(address[],uint256[])": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "verifyRelayManagerStaked(address)": FunctionFragment;
    "versionHub()": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
    "withdrawMultiple(address[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addRelayWorkers",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "aggregateGasleft",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "calculateCharge",
    values: [BigNumberish, GsnTypes.RelayDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateDevCharge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "depositFor", values: [string]): string;
  encodeFunctionData(
    functionFragment: "deprecateHub",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escheatAbandonedRelayBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchGateway",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreationBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDeprecationTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumStakePerToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPenalizer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRelayRegistrar",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerCount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkerManager",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isDeprecated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRelayEscheatable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "onRelayServerRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "penalize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "relayCall",
    values: [
      string,
      BigNumberish,
      GsnTypes.RelayRequestStruct,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfiguration",
    values: [IRelayHub.RelayHubConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumStakes",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyRelayManagerStaked",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "versionHub",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawMultiple",
    values: [string[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addRelayWorkers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregateGasleft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateCharge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateDevCharge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deprecateHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escheatAbandonedRelayBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreationBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeprecationTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumStakePerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPenalizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRelayRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkerManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDeprecated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRelayEscheatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onRelayServerRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "penalize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "relayCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyRelayManagerStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "versionHub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawMultiple",
    data: BytesLike
  ): Result;

  events: {
    "AbandonedRelayManagerBalanceEscheated(address,uint256)": EventFragment;
    "Deposited(address,address,uint256)": EventFragment;
    "HubDeprecated(uint256)": EventFragment;
    "RelayHubConfigured(tuple)": EventFragment;
    "RelayWorkersAdded(address,address[],uint256)": EventFragment;
    "StakingTokenDataChanged(address,uint256)": EventFragment;
    "TransactionRejectedByPaymaster(address,address,bytes32,address,address,address,bytes4,uint256,bytes)": EventFragment;
    "TransactionRelayed(address,address,bytes32,address,address,address,bytes4,uint8,uint256)": EventFragment;
    "TransactionResult(uint8,bytes)": EventFragment;
    "Withdrawn(address,address,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AbandonedRelayManagerBalanceEscheated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HubDeprecated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayHubConfigured"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayWorkersAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakingTokenDataChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "TransactionRejectedByPaymaster"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransactionRelayed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransactionResult"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
}

export type AbandonedRelayManagerBalanceEscheatedEvent = TypedEvent<
  [string, BigNumber],
  { relayManager: string; balance: BigNumber }
>;

export type AbandonedRelayManagerBalanceEscheatedEventFilter =
  TypedEventFilter<AbandonedRelayManagerBalanceEscheatedEvent>;

export type DepositedEvent = TypedEvent<
  [string, string, BigNumber],
  { paymaster: string; from: string; amount: BigNumber }
>;

export type DepositedEventFilter = TypedEventFilter<DepositedEvent>;

export type HubDeprecatedEvent = TypedEvent<
  [BigNumber],
  { deprecationTime: BigNumber }
>;

export type HubDeprecatedEventFilter = TypedEventFilter<HubDeprecatedEvent>;

export type RelayHubConfiguredEvent = TypedEvent<
  [IRelayHub.RelayHubConfigStructOutput],
  { config: IRelayHub.RelayHubConfigStructOutput }
>;

export type RelayHubConfiguredEventFilter =
  TypedEventFilter<RelayHubConfiguredEvent>;

export type RelayWorkersAddedEvent = TypedEvent<
  [string, string[], BigNumber],
  { relayManager: string; newRelayWorkers: string[]; workersCount: BigNumber }
>;

export type RelayWorkersAddedEventFilter =
  TypedEventFilter<RelayWorkersAddedEvent>;

export type StakingTokenDataChangedEvent = TypedEvent<
  [string, BigNumber],
  { token: string; minimumStake: BigNumber }
>;

export type StakingTokenDataChangedEventFilter =
  TypedEventFilter<StakingTokenDataChangedEvent>;

export type TransactionRejectedByPaymasterEvent = TypedEvent<
  [string, string, string, string, string, string, string, BigNumber, string],
  {
    relayManager: string;
    paymaster: string;
    relayRequestID: string;
    from: string;
    to: string;
    relayWorker: string;
    selector: string;
    innerGasUsed: BigNumber;
    reason: string;
  }
>;

export type TransactionRejectedByPaymasterEventFilter =
  TypedEventFilter<TransactionRejectedByPaymasterEvent>;

export type TransactionRelayedEvent = TypedEvent<
  [string, string, string, string, string, string, string, number, BigNumber],
  {
    relayManager: string;
    relayWorker: string;
    relayRequestID: string;
    from: string;
    to: string;
    paymaster: string;
    selector: string;
    status: number;
    charge: BigNumber;
  }
>;

export type TransactionRelayedEventFilter =
  TypedEventFilter<TransactionRelayedEvent>;

export type TransactionResultEvent = TypedEvent<
  [number, string],
  { status: number; returnValue: string }
>;

export type TransactionResultEventFilter =
  TypedEventFilter<TransactionResultEvent>;

export type WithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  { account: string; dest: string; amount: BigNumber }
>;

export type WithdrawnEventFilter = TypedEventFilter<WithdrawnEvent>;

export interface IRelayHub extends BaseContract {
  contractName: "IRelayHub";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRelayHubInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addRelayWorkers(
      newRelayWorkers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    aggregateGasleft(overrides?: CallOverrides): Promise<[BigNumber]>;

    balanceOf(target: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    calculateCharge(
      gasUsed: BigNumberish,
      relayData: GsnTypes.RelayDataStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    calculateDevCharge(
      charge: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    depositFor(
      target: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deprecateHub(
      _deprecationTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    escheatAbandonedRelayBalance(
      relayManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getBatchGateway(overrides?: CallOverrides): Promise<[string]>;

    getConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [IRelayHub.RelayHubConfigStructOutput] & {
        config: IRelayHub.RelayHubConfigStructOutput;
      }
    >;

    getCreationBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    getDeprecationTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMinimumStakePerToken(
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPenalizer(overrides?: CallOverrides): Promise<[string]>;

    getRelayRegistrar(overrides?: CallOverrides): Promise<[string]>;

    getStakeManager(overrides?: CallOverrides): Promise<[string]>;

    getWorkerCount(
      manager: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getWorkerManager(
      worker: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isDeprecated(overrides?: CallOverrides): Promise<[boolean]>;

    isRelayEscheatable(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    onRelayServerRegistered(
      relayManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    penalize(
      relayWorker: string,
      beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    relayCall(
      domainSeparatorName: string,
      maxAcceptanceBudget: BigNumberish,
      relayRequest: GsnTypes.RelayRequestStruct,
      signature: BytesLike,
      approvalData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setConfiguration(
      _config: IRelayHub.RelayHubConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMinimumStakes(
      token: string[],
      minimumStake: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    verifyRelayManagerStaked(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<[void]>;

    versionHub(overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      dest: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawMultiple(
      dest: string[],
      amount: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addRelayWorkers(
    newRelayWorkers: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  aggregateGasleft(overrides?: CallOverrides): Promise<BigNumber>;

  balanceOf(target: string, overrides?: CallOverrides): Promise<BigNumber>;

  calculateCharge(
    gasUsed: BigNumberish,
    relayData: GsnTypes.RelayDataStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculateDevCharge(
    charge: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  depositFor(
    target: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deprecateHub(
    _deprecationTime: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  escheatAbandonedRelayBalance(
    relayManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getBatchGateway(overrides?: CallOverrides): Promise<string>;

  getConfiguration(
    overrides?: CallOverrides
  ): Promise<IRelayHub.RelayHubConfigStructOutput>;

  getCreationBlock(overrides?: CallOverrides): Promise<BigNumber>;

  getDeprecationTime(overrides?: CallOverrides): Promise<BigNumber>;

  getMinimumStakePerToken(
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPenalizer(overrides?: CallOverrides): Promise<string>;

  getRelayRegistrar(overrides?: CallOverrides): Promise<string>;

  getStakeManager(overrides?: CallOverrides): Promise<string>;

  getWorkerCount(
    manager: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWorkerManager(worker: string, overrides?: CallOverrides): Promise<string>;

  isDeprecated(overrides?: CallOverrides): Promise<boolean>;

  isRelayEscheatable(
    relayManager: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  onRelayServerRegistered(
    relayManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  penalize(
    relayWorker: string,
    beneficiary: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  relayCall(
    domainSeparatorName: string,
    maxAcceptanceBudget: BigNumberish,
    relayRequest: GsnTypes.RelayRequestStruct,
    signature: BytesLike,
    approvalData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setConfiguration(
    _config: IRelayHub.RelayHubConfigStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMinimumStakes(
    token: string[],
    minimumStake: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  verifyRelayManagerStaked(
    relayManager: string,
    overrides?: CallOverrides
  ): Promise<void>;

  versionHub(overrides?: CallOverrides): Promise<string>;

  withdraw(
    dest: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawMultiple(
    dest: string[],
    amount: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addRelayWorkers(
      newRelayWorkers: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    aggregateGasleft(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(target: string, overrides?: CallOverrides): Promise<BigNumber>;

    calculateCharge(
      gasUsed: BigNumberish,
      relayData: GsnTypes.RelayDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateDevCharge(
      charge: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositFor(target: string, overrides?: CallOverrides): Promise<void>;

    deprecateHub(
      _deprecationTime: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    escheatAbandonedRelayBalance(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getBatchGateway(overrides?: CallOverrides): Promise<string>;

    getConfiguration(
      overrides?: CallOverrides
    ): Promise<IRelayHub.RelayHubConfigStructOutput>;

    getCreationBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getDeprecationTime(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumStakePerToken(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenalizer(overrides?: CallOverrides): Promise<string>;

    getRelayRegistrar(overrides?: CallOverrides): Promise<string>;

    getStakeManager(overrides?: CallOverrides): Promise<string>;

    getWorkerCount(
      manager: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWorkerManager(
      worker: string,
      overrides?: CallOverrides
    ): Promise<string>;

    isDeprecated(overrides?: CallOverrides): Promise<boolean>;

    isRelayEscheatable(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    onRelayServerRegistered(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    penalize(
      relayWorker: string,
      beneficiary: string,
      overrides?: CallOverrides
    ): Promise<void>;

    relayCall(
      domainSeparatorName: string,
      maxAcceptanceBudget: BigNumberish,
      relayRequest: GsnTypes.RelayRequestStruct,
      signature: BytesLike,
      approvalData: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [boolean, BigNumber, number, string] & {
        paymasterAccepted: boolean;
        charge: BigNumber;
        status: number;
        returnValue: string;
      }
    >;

    setConfiguration(
      _config: IRelayHub.RelayHubConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinimumStakes(
      token: string[],
      minimumStake: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    verifyRelayManagerStaked(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    versionHub(overrides?: CallOverrides): Promise<string>;

    withdraw(
      dest: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawMultiple(
      dest: string[],
      amount: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AbandonedRelayManagerBalanceEscheated(address,uint256)"(
      relayManager?: string | null,
      balance?: null
    ): AbandonedRelayManagerBalanceEscheatedEventFilter;
    AbandonedRelayManagerBalanceEscheated(
      relayManager?: string | null,
      balance?: null
    ): AbandonedRelayManagerBalanceEscheatedEventFilter;

    "Deposited(address,address,uint256)"(
      paymaster?: string | null,
      from?: string | null,
      amount?: null
    ): DepositedEventFilter;
    Deposited(
      paymaster?: string | null,
      from?: string | null,
      amount?: null
    ): DepositedEventFilter;

    "HubDeprecated(uint256)"(deprecationTime?: null): HubDeprecatedEventFilter;
    HubDeprecated(deprecationTime?: null): HubDeprecatedEventFilter;

    "RelayHubConfigured(tuple)"(config?: null): RelayHubConfiguredEventFilter;
    RelayHubConfigured(config?: null): RelayHubConfiguredEventFilter;

    "RelayWorkersAdded(address,address[],uint256)"(
      relayManager?: string | null,
      newRelayWorkers?: null,
      workersCount?: null
    ): RelayWorkersAddedEventFilter;
    RelayWorkersAdded(
      relayManager?: string | null,
      newRelayWorkers?: null,
      workersCount?: null
    ): RelayWorkersAddedEventFilter;

    "StakingTokenDataChanged(address,uint256)"(
      token?: null,
      minimumStake?: null
    ): StakingTokenDataChangedEventFilter;
    StakingTokenDataChanged(
      token?: null,
      minimumStake?: null
    ): StakingTokenDataChangedEventFilter;

    "TransactionRejectedByPaymaster(address,address,bytes32,address,address,address,bytes4,uint256,bytes)"(
      relayManager?: string | null,
      paymaster?: string | null,
      relayRequestID?: BytesLike | null,
      from?: null,
      to?: null,
      relayWorker?: null,
      selector?: null,
      innerGasUsed?: null,
      reason?: null
    ): TransactionRejectedByPaymasterEventFilter;
    TransactionRejectedByPaymaster(
      relayManager?: string | null,
      paymaster?: string | null,
      relayRequestID?: BytesLike | null,
      from?: null,
      to?: null,
      relayWorker?: null,
      selector?: null,
      innerGasUsed?: null,
      reason?: null
    ): TransactionRejectedByPaymasterEventFilter;

    "TransactionRelayed(address,address,bytes32,address,address,address,bytes4,uint8,uint256)"(
      relayManager?: string | null,
      relayWorker?: string | null,
      relayRequestID?: BytesLike | null,
      from?: null,
      to?: null,
      paymaster?: null,
      selector?: null,
      status?: null,
      charge?: null
    ): TransactionRelayedEventFilter;
    TransactionRelayed(
      relayManager?: string | null,
      relayWorker?: string | null,
      relayRequestID?: BytesLike | null,
      from?: null,
      to?: null,
      paymaster?: null,
      selector?: null,
      status?: null,
      charge?: null
    ): TransactionRelayedEventFilter;

    "TransactionResult(uint8,bytes)"(
      status?: null,
      returnValue?: null
    ): TransactionResultEventFilter;
    TransactionResult(
      status?: null,
      returnValue?: null
    ): TransactionResultEventFilter;

    "Withdrawn(address,address,uint256)"(
      account?: string | null,
      dest?: string | null,
      amount?: null
    ): WithdrawnEventFilter;
    Withdrawn(
      account?: string | null,
      dest?: string | null,
      amount?: null
    ): WithdrawnEventFilter;
  };

  estimateGas: {
    addRelayWorkers(
      newRelayWorkers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    aggregateGasleft(overrides?: CallOverrides): Promise<BigNumber>;

    balanceOf(target: string, overrides?: CallOverrides): Promise<BigNumber>;

    calculateCharge(
      gasUsed: BigNumberish,
      relayData: GsnTypes.RelayDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateDevCharge(
      charge: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositFor(
      target: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deprecateHub(
      _deprecationTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    escheatAbandonedRelayBalance(
      relayManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getBatchGateway(overrides?: CallOverrides): Promise<BigNumber>;

    getConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getCreationBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getDeprecationTime(overrides?: CallOverrides): Promise<BigNumber>;

    getMinimumStakePerToken(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPenalizer(overrides?: CallOverrides): Promise<BigNumber>;

    getRelayRegistrar(overrides?: CallOverrides): Promise<BigNumber>;

    getStakeManager(overrides?: CallOverrides): Promise<BigNumber>;

    getWorkerCount(
      manager: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWorkerManager(
      worker: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isDeprecated(overrides?: CallOverrides): Promise<BigNumber>;

    isRelayEscheatable(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onRelayServerRegistered(
      relayManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    penalize(
      relayWorker: string,
      beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    relayCall(
      domainSeparatorName: string,
      maxAcceptanceBudget: BigNumberish,
      relayRequest: GsnTypes.RelayRequestStruct,
      signature: BytesLike,
      approvalData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setConfiguration(
      _config: IRelayHub.RelayHubConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMinimumStakes(
      token: string[],
      minimumStake: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    verifyRelayManagerStaked(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    versionHub(overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      dest: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawMultiple(
      dest: string[],
      amount: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addRelayWorkers(
      newRelayWorkers: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    aggregateGasleft(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    balanceOf(
      target: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateCharge(
      gasUsed: BigNumberish,
      relayData: GsnTypes.RelayDataStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculateDevCharge(
      charge: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositFor(
      target: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deprecateHub(
      _deprecationTime: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    escheatAbandonedRelayBalance(
      relayManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getBatchGateway(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getConfiguration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCreationBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDeprecationTime(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMinimumStakePerToken(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPenalizer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getRelayRegistrar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getStakeManager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWorkerCount(
      manager: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWorkerManager(
      worker: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isDeprecated(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isRelayEscheatable(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onRelayServerRegistered(
      relayManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    penalize(
      relayWorker: string,
      beneficiary: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    relayCall(
      domainSeparatorName: string,
      maxAcceptanceBudget: BigNumberish,
      relayRequest: GsnTypes.RelayRequestStruct,
      signature: BytesLike,
      approvalData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setConfiguration(
      _config: IRelayHub.RelayHubConfigStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMinimumStakes(
      token: string[],
      minimumStake: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyRelayManagerStaked(
      relayManager: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    versionHub(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdraw(
      dest: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawMultiple(
      dest: string[],
      amount: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
