apiVersion: v1
kind: Service
metadata:
  name: openalex-importer-service
  labels:
    App: OpenAlexImporter
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      App: OpenAlexImporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: app-vault-reader
        vault.hashicorp.com/agent-inject-secret-config: secrets/openalex/db
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secrets/desci-server/dev/repo" -}}
          echo "sourcing";
          export OPENALEX_API_KEY={{ .Data.OPENALEX_API_KEY }}
          export NODE_ENV=production
          export DATABASE_URL={{ .Data.DATABASE_URL }}
          {{- end -}}
      labels:
        App: OpenAlexImporter
    spec:
      containers:
        - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/openalex-importer:latest
          name: openalex-importer
          command: ['/bin/bash', '-c']
          args:
            - echo "SOURCING ENV"; source /vault/secrets/config; NODE_PATH=./dist node ./dist/index.js;
          resources:
            limits:
              cpu: '2'
              memory: 16Gi
            requests:
              cpu: '1'
              memory: 8Gi
      serviceAccountName: 'vault-auth'
