apiVersion: apps/v1
kind: Deployment
metadata:
  name: desci-media-isolated-dev
  labels:
    App: DesciMediaIsolatedDev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      App: DesciMediaIsolatedDev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        App: DesciMediaIsolatedDev
    spec:
      containers:
        - image: 523044037273.dkr.ecr.us-east-2.amazonaws.com/desci-media-isolated-dev:production
          name: desci-media-isolated-dev
          ports:
            - containerPort: 7771
              name: media_isolated_dev
          env:
            - name: PORT
              value: '7771'
            - name: IPFS_GATEWAY
              value: 'http://host.docker.internal:5420/v1/ipfs'
          resources:
            limits:
              cpu: '0.5'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
      serviceAccountName: 'default'
