name: 'Bug Report'
description: 'File a bug report'
body:
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'A clear and concise description of what the bug is.'
      placeholder: |
        Bug description
    validations:
      required: true
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        Add any other context about the problem here.
