"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.ERC165Upgradeable__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        anonymous: false,
        inputs: [
            {
                indexed: false,
                internalType: "uint8",
                name: "version",
                type: "uint8"
            },
        ],
        name: "Initialized",
        type: "event"
    },
    {
        inputs: [
            {
                internalType: "bytes4",
                name: "interfaceId",
                type: "bytes4"
            },
        ],
        name: "supportsInterface",
        outputs: [
            {
                internalType: "bool",
                name: "",
                type: "bool"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
];
var ERC165Upgradeable__factory = /** @class */ (function () {
    function ERC165Upgradeable__factory() {
    }
    ERC165Upgradeable__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ERC165Upgradeable__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ERC165Upgradeable__factory.abi = _abi;
    return ERC165Upgradeable__factory;
}());
exports.ERC165Upgradeable__factory = ERC165Upgradeable__factory;
