"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IDpidRegistry__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "prefix",
                type: "bytes32"
            },
            {
                internalType: "uint256",
                name: "entryId",
                type: "uint256"
            },
        ],
        name: "get",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "prefix",
                type: "bytes32"
            },
        ],
        name: "getOrganization",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
            {
                internalType: "address",
                name: "",
                type: "address"
            },
        ],
        stateMutability: "view",
        type: "function"
    },
    {
        inputs: [
            {
                internalType: "bytes32",
                name: "prefix",
                type: "bytes32"
            },
            {
                internalType: "uint256",
                name: "entry",
                type: "uint256"
            },
        ],
        name: "put",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256"
            },
        ],
        stateMutability: "payable",
        type: "function"
    },
];
var IDpidRegistry__factory = /** @class */ (function () {
    function IDpidRegistry__factory() {
    }
    IDpidRegistry__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IDpidRegistry__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IDpidRegistry__factory.abi = _abi;
    return IDpidRegistry__factory;
}());
exports.IDpidRegistry__factory = IDpidRegistry__factory;
