/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IDpidRegistry, IDpidRegistryInterface } from "../IDpidRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prefix",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "entryId",
        type: "uint256",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prefix",
        type: "bytes32",
      },
    ],
    name: "getOrganization",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "prefix",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "entry",
        type: "uint256",
      },
    ],
    name: "put",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IDpidRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IDpidRegistryInterface {
    return new utils.Interface(_abi) as IDpidRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDpidRegistry {
    return new Contract(address, _abi, signerOrProvider) as IDpidRegistry;
  }
}
