"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
exports.__esModule = true;
exports.IERC721ReceiverUpgradeable__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "operator",
                type: "address"
            },
            {
                internalType: "address",
                name: "from",
                type: "address"
            },
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256"
            },
            {
                internalType: "bytes",
                name: "data",
                type: "bytes"
            },
        ],
        name: "onERC721Received",
        outputs: [
            {
                internalType: "bytes4",
                name: "",
                type: "bytes4"
            },
        ],
        stateMutability: "nonpayable",
        type: "function"
    },
];
var IERC721ReceiverUpgradeable__factory = /** @class */ (function () {
    function IERC721ReceiverUpgradeable__factory() {
    }
    IERC721ReceiverUpgradeable__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IERC721ReceiverUpgradeable__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IERC721ReceiverUpgradeable__factory.abi = _abi;
    return IERC721ReceiverUpgradeable__factory;
}());
exports.IERC721ReceiverUpgradeable__factory = IERC721ReceiverUpgradeable__factory;
