/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC2771RecipientUpgradeable,
  IERC2771RecipientUpgradeableInterface,
} from "../IERC2771RecipientUpgradeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IERC2771RecipientUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC2771RecipientUpgradeableInterface {
    return new utils.Interface(_abi) as IERC2771RecipientUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC2771RecipientUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC2771RecipientUpgradeable;
  }
}
