# Top-level configuration
name = "automerge-sync-server"
main = "src/party/Automerge.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "Automerge"
class_name = "AutomergeServer"

[vars]
DATABASE_URL= "postgresql://walter:white@host.docker.internal:5432/boilerplate"
DB_TABLE= "DocumentStore"
NODES_API= "http://localhost:5420"
ENVIRONMENT="local"

[[migrations]]
tag = "v1"
new_classes = ["AutomergeServer"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[hyperdrive]]
binding = "NODES_DB"
id = "856af129675e4140accc0ccabbc2ee20"
localConnectionString = "postgresql://walter:white@host.docker.internal:5432/boilerplate"