# build.yml
on:
  # pull_request:
  #   paths:
  #   - desci-server/**
  push:
    paths:
      - .github/workflows/**
      - desci-server/**
      - desci-contracts/**
      - sync-server/**
      - integrationTestRunner.sh
      - docker-compose.test.yml

name: Test desci-server

jobs:
  build-and-test:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Enable blacksmith docker layer caching
      #- uses: useblacksmith/setup-docker-builder@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pre-pull ceramic-one image
        run: |
          docker pull 523044037273.dkr.ecr.us-east-2.amazonaws.com/ceramic-one:latest || echo "Pull failed, will retry during docker-compose"

      - name: Run tests
        run:
          SKIP_NODES_LIB=1 ./integrationTestRunner.sh
