# build.yml
on:
  # pull_request:
  #   paths:
  #   - desci-server/**
  push:
    paths:
      - .github/workflows/**
      - desci-server/**
      - desci-contracts/**
      - integrationTestRunner.sh
      - docker-compose.test.yml
    branches: # array of glob patterns matching against refs/heads. Optional; defaults to all
      - main # triggers on pushes that contain changes
      - develop
      - demo

name: Build desci-server

# https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
env:
  AWS_DEFAULT_REGION: us-east-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  CONTAINER_IMAGE: desci-server
  DOCKER_BUILDKIT: 1

jobs:
  build-and-test:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          check-latest: false
          cache: "yarn"
          cache-dependency-path: |
            desci-server/yarn.lock

      # Enable blacksmith docker layer caching
      #- uses: useblacksmith/setup-docker-builder@v1

      - name: Install dependencies (desci-server)
        working-directory: desci-server
        run: yarn install --ignore-engines --frozen-lockfile

      - name: Run tests
        run: |
          SKIP_NODES_LIB=1 ./integrationTestRunner.sh

  build-and-push-images:
    # we build and push for every commit, even if tests pass, that way when tests pass deployment is short (run test + build in parallel)
    name: Build and push images
    runs-on: blacksmith-4vcpu-ubuntu-2204
    outputs:
      image_tag: ${{ steps.image-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tag
        id: image-tag
        run: echo "tag=$(echo ${{ github.sha }} | cut -c1-7)-$(date +%s)" >> $GITHUB_OUTPUT

      # Enable blacksmith docker layer caching
      #- uses: useblacksmith/setup-docker-builder@v1

      - name: Build and tag the image (DEV)
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build \
            --secret id=SENTRY_AUTH_TOKEN \
            -f desci-server/Dockerfile.ci \
            -t $CONTAINER_IMAGE-dev:${{ github.sha }} \
            -t $CONTAINER_IMAGE-dev:${{ steps.image-tag.outputs.tag }} \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-dev \
             ./desci-server

      - name: Build and tag the image (DEMO)
        if: github.ref == 'refs/heads/demo'
        run: |
          docker build \
            --secret id=SENTRY_AUTH_TOKEN \
            -f desci-server/Dockerfile.ci \
            -t $CONTAINER_IMAGE-demo:${{ github.sha }} \
            -t $CONTAINER_IMAGE-demo:${{ steps.image-tag.outputs.tag }} \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-demo \
             ./desci-server

      - name: Build and tag the image (PROD)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build \
            --secret id=SENTRY_AUTH_TOKEN \
            -f desci-server/Dockerfile.ci \
            -t $CONTAINER_IMAGE:${{ github.sha }} \
            -t $CONTAINER_IMAGE:${{ steps.image-tag.outputs.tag }} \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE \
             ./desci-server

      - name: Push (DEV)
        if: github.ref == 'refs/heads/develop'
        run: |
          # Push image to AWS ECR
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          docker tag $CONTAINER_IMAGE-dev:${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-dev:${{ github.sha }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-dev:${{ github.sha }}
          docker tag $CONTAINER_IMAGE-dev:${{ steps.image-tag.outputs.tag }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-dev:${{ steps.image-tag.outputs.tag }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-dev:${{ steps.image-tag.outputs.tag }}

      - name: Push (DEMO)
        if: github.ref == 'refs/heads/demo'
        run: |
          # Push image to AWS ECR
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          docker tag $CONTAINER_IMAGE-demo:${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-demo:${{ github.sha }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-demo:${{ github.sha }}
          docker tag $CONTAINER_IMAGE-demo:${{ steps.image-tag.outputs.tag }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-demo:${{ steps.image-tag.outputs.tag }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE-demo:${{ steps.image-tag.outputs.tag }}

      - name: Push (PROD)
        if: github.ref == 'refs/heads/main'
        run: |
          # Push image to AWS ECR
          aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
          docker tag $CONTAINER_IMAGE:${{ github.sha }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE:${{ github.sha }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE:${{ github.sha }}
          docker tag $CONTAINER_IMAGE:${{ steps.image-tag.outputs.tag }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE:${{ steps.image-tag.outputs.tag }}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE:${{ steps.image-tag.outputs.tag }}
