on:
  pull_request:
    paths:
      - .github/workflows/check-media.yml
      - nodes-media/**
jobs:
  check-media:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          check-latest: false
          cache: "yarn"
          cache-dependency-path: "nodes-media/yarn.lock"

      - name: Install dependencies
        run: |
          cd nodes-media
          yarn

      - name: Build project
        run: |
          cd nodes-media
          npx tsc --noEmit
