name: Deploy Worker
on:
  push:
    paths:
      - .github/workflows/deploy-sync-server.yaml
      - sync-server/**
    branches: # array of glob patterns matching against refs/heads. Optional; defaults to all
      - main # triggers on pushes that contain changes
      - develop
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker (Staging)
        if: github.ref == 'refs/heads/develop'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_DEV }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: staging
          workingDirectory: sync-server
          wranglerVersion: 3.95.0
          secrets: API_TOKEN

      - name: Build & Deploy Worker (Production)
        if: github.ref == 'refs/heads/main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_PROD }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: production
          workingDirectory: sync-server
          wranglerVersion: 3.95.0
          secrets: API_TOKEN
