# build.yml
on:
  # pull_request:
  #   paths:
  #   - .github/workflows/**
  #   - desci-models/**
  push:
    paths:
      - .github/workflows/**
      - desci-models/**

name: Test desci-models

jobs:
  build-and-test:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    # container:
    #   image: ubuntu:latest
    #   options: --user 1001

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up the environment
        # Replace this line with the appropriate setup for your project
        # Examples:
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          check-latest: false
          cache: "yarn"
          cache-dependency-path: "desci-models/yarn.lock"

      - name: Install dependencies
        run: cd desci-models && npm i -g yarn && yarn && yarn build

      - name: Run tests
        run: |
          cd desci-models && yarn generate && yarn test
