# build.yml
on:
  # pull_request:
  #   paths:
  #   - .github/workflows/**
  #   - desci-models/**
  push:
    paths:
      - .github/workflows/**
      - desci-models/**

name: Test desci-models

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # container:
    #   image: ubuntu:latest
    #   options: --user 1001

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up the environment
        # Replace this line with the appropriate setup for your project
        # Examples:
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          check-latest: false
          cache: "yarn"
          cache-dependency-path: "desci-models/yarn.lock"

      - name: Set up docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo docker-compose --version
          docker info

      - name: Install dependencies
        run: cd desci-models && npm i -g yarn && yarn && yarn build

      - name: Run tests
        run: |
          cd desci-models && yarn generate && yarn test
