on:
  push:
    paths:
      - .github/workflows/**
      - nodes-lib/**
      - desci-server/**
      - desci-contracts/**
      - integrationTestRunner.sh
      - docker-compose.test.yml
env:
  PRIVATE_KEY: ${{ secrets.CERAMIC_ADMIN_SEED }}
jobs:
  test-nodes-lib:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      # Enable blacksmith docker layer caching
      - uses: useblacksmith/setup-docker-builder@v1

      - name: Run tests
        run: |
          SKIP_SERVER=1 ./integrationTestRunner.sh
