on:
  workflow_dispatch:

name: Publish desci-models

jobs:
  publish-models:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up the environment
        # Replace this line with the appropriate setup for your project
        # Examples:
        uses: useblacksmith/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          check-latest: false
          cache: "yarn"
          cache-dependency-path: "desci-models/yarn.lock"

      - name: Install dependencies
        run: cd desci-models && npm i -g yarn && yarn && yarn build

      - name: Login to npm
        run: npm set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Check version
        run: |
          cd desci-models && npm version --no-git-tag-version
          echo "Version: $(cat desci-models/package.json | jq -r '.version')"

      - name: Publish models
        run: |
          cd desci-models && npm publish --access public --tag latest
