name: Test Server

on:
  pull_request:
    branches:
      - main
      - develop

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --user 1001

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up the environment
        # Replace this line with the appropriate setup for your project
        # Examples:
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd desci-models && npm i -g yarn && yarn && yarn build && cd ../desci-server && yarn

      - name: Stub contract
        run: |
          echo "{\"proxies\":[{\"address\":\"\"}]}" > desci-server/src/desci-contracts-config/unknown-research-object.json
          echo "{\"proxies\":[{\"address\":\"\"}]}" > desci-server/src/desci-contracts-config/unknown-dpid.json

      - name: Run tests
        run: cd desci-server && export DOCKER_BUILDKIT=1 && yarn && yarn test
