name: Test Server

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up the environment
        # Replace this line with the appropriate setup for your project
        # Examples:
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: cd desci-server && yarn

      - name: Run tests
        run: yarn test
