name: Test Server

on:
  pull_request:
    branches:
      - main
      - develop

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up the environment
        # Replace this line with the appropriate setup for your project
        # Examples:
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check Docker Version
        run: docker --version
      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce
      - name: Check Docker Version
        run: docker --version

      - name: Install dependencies
        run: cd desci-models && yarn && yarn build && cd ../desci-server && yarn

      - name: Run tests
        run: cd desci-server && yarn test
